In [160]:
# importing libraries  
import numpy as np  
import matplotlib.pyplot as plt
import pandas as pd 

In [161]:
#importing datasets  
df = pd.read_csv('glass.csv')  

In [162]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [163]:
df['Type'].unique()

array([1, 2, 3, 5, 6, 7], dtype=int64)

In [164]:
#Extracting Independent and dependent Variable  
x= df.iloc[:, :-1].values  
y= df.iloc[:, 9].values  

#### Create and train logistic regression model

In [165]:
#importing the LogisticRegression 
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [166]:
from sklearn.model_selection import train_test_split

In [167]:
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)  

In [168]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [169]:
x_train

array([[ 1.51784, 12.68   ,  3.67   , ...,  8.7    ,  0.     ,  0.     ],
       [ 1.51789, 13.19   ,  3.9    , ...,  8.44   ,  0.     ,  0.28   ],
       [ 1.51687, 13.23   ,  3.54   , ...,  8.1    ,  0.     ,  0.     ],
       ...,
       [ 1.51708, 13.72   ,  3.68   , ...,  7.88   ,  0.     ,  0.     ],
       [ 1.52667, 13.99   ,  3.7    , ...,  9.82   ,  0.     ,  0.1    ],
       [ 1.51321, 13.     ,  0.     , ...,  6.93   ,  0.     ,  0.     ]])

In [170]:
model.fit(x, y)

C:\Users\Lovely\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [171]:
model.predict([[1.51,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.0]])

array([1], dtype=int64)

### Measure accuracy of our model

In [172]:
model.score(x_train,y_train)

0.672514619883041